document.addEventListener("DOMContentLoaded", () => {
  const modal = document.getElementById("booking-modal");
  if (!modal) return;
  const form = document.getElementById("booking-form");
  const catalog = window.vehicleCatalog || {};
  const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  const phonePattern = /^\d{10}$/;
  let selectedVehicle = "";
  form.innerHTML = `<input id="booking-vehicle-input" name="vehicle" type="hidden"><input id="booking-model-year" name="modelYear" type="hidden"><p class="booking-summary" id="booking-summary"></p><fieldset class="customer-type"><legend>Customer type</legend><label><input type="radio" name="customerType" value="indian" checked> Indian Resident</label><label><input type="radio" name="customerType" value="nri"> NRI</label></fieldset><p class="kyc-note">These are demo platform verification requirements and may differ by rental provider.</p><div class="booking-fields" id="booking-fields"></div><div class="booking-date-row"><div><label for="pickup-date">Pickup date</label><input id="pickup-date" name="pickup" type="date" required></div><div><label for="return-date">Return date</label><input id="return-date" name="return" type="date" required></div></div><p id="booking-error" class="booking-error" role="alert" aria-live="polite"></p><button class="btn btn-primary" type="submit">Confirm Booking</button><p id="booking-success" class="booking-success" role="status"></p>`;
  const fields = document.getElementById("booking-fields"), error = document.getElementById("booking-error"), success = document.getElementById("booking-success");
  const renderFields = () => {
    const nri = form.elements.customerType.value === "nri";
    fields.innerHTML = nri ? `<label for="booking-name">Full name</label><input id="booking-name" name="name" autocomplete="name" required><label for="booking-phone">Mobile number</label><input id="booking-phone" name="phone" type="tel" inputmode="numeric" required><label for="booking-email">Email</label><input id="booking-email" name="email" type="email" autocomplete="email" required><label for="passport-number">Passport number</label><input id="passport-number" name="passport" required><label for="driving-authorisation">Driving licence / applicable driving authorization</label><input id="driving-authorisation" name="drivingAuthorisation" required><label for="residence-country">Country of residence</label><input id="residence-country" name="country" required><label for="overseas-address">Overseas address</label><textarea id="overseas-address" name="address" required></textarea>` : `<label for="booking-name">Full name</label><input id="booking-name" name="name" autocomplete="name" required><label for="booking-phone">Mobile number</label><input id="booking-phone" name="phone" type="tel" inputmode="numeric" required><label for="booking-email">Email</label><input id="booking-email" name="email" type="email" autocomplete="email" required><label for="licence-number">Driving licence number</label><input id="licence-number" name="licence" required><label for="government-id-type">Government ID type</label><select id="government-id-type" name="governmentIdType" required><option value="">Select ID type</option><option>Aadhaar</option><option>Voter ID</option><option>Passport</option></select><label for="government-id-number">Government ID number</label><input id="government-id-number" name="governmentIdNumber" required><label for="customer-address">Address</label><textarea id="customer-address" name="address" required></textarea>`;
  };
  const close = () => { modal.hidden = true; modal.setAttribute("aria-hidden", "true"); };
  const open = (vehicle) => { selectedVehicle = vehicle; const data = Object.values(catalog).find((item) => item.name === vehicle); form.reset(); renderFields(); error.textContent = ""; success.textContent = ""; document.getElementById("booking-vehicle").textContent = vehicle; form.elements.vehicle.value = vehicle; form.elements.modelYear.value = data?.modelYear || ""; document.getElementById("booking-summary").textContent = data ? `${data.category} • Model Year: ${data.modelYear} • ₹${data.price.toLocaleString("en-IN")}/day` : ""; modal.hidden = false; modal.setAttribute("aria-hidden", "false"); document.getElementById("booking-name").focus(); };
  document.querySelectorAll(".book-button").forEach((button) => button.addEventListener("click", () => open(button.dataset.vehicle)));
  form.addEventListener("change", (event) => { if (event.target.name === "customerType") { renderFields(); error.textContent = ""; } });
  modal.querySelectorAll("[data-close-booking]").forEach((button) => button.addEventListener("click", close));
  document.addEventListener("keydown", (event) => { if (event.key === "Escape" && !modal.hidden) close(); });
  form.addEventListener("submit", (event) => { event.preventDefault(); const data = Object.fromEntries(new FormData(form).entries()); const required = [...fields.querySelectorAll("[required]")]; const missing = required.some((input) => !input.value.trim()); if (missing || !emailPattern.test(data.email || "") || !phonePattern.test(data.phone || "") || !data.pickup || !data.return || data.return < data.pickup) { error.textContent = missing ? "Complete all required KYC fields." : "Enter a valid email, 10-digit phone number, and valid rental dates."; required.find((input) => !input.value.trim())?.focus(); return; } const bookings = JSON.parse(localStorage.getItem("drivora-bookings") || "[]"); const booking = { id: Date.now(), vehicle: selectedVehicle, modelYear: data.modelYear, name: data.name, phone: data.phone, email: data.email, pickup: data.pickup, returnDate: data.return, customerType: data.customerType, kycStatus: "Pending Verification", createdAt: new Date().toISOString() }; bookings.push(booking); localStorage.setItem("drivora-bookings", JSON.stringify(bookings)); const kyc = JSON.parse(localStorage.getItem("drivora-kyc-data") || "[]"); kyc.push({ bookingId: booking.id, vehicle: selectedVehicle, customerType: data.customerType, name: data.name, email: data.email, phone: data.phone, kycStatus: "Pending Verification", submittedAt: booking.createdAt }); localStorage.setItem("drivora-kyc-data", JSON.stringify(kyc)); error.textContent = ""; success.textContent = "KYC Status: Pending Verification. Booking confirmed for demo review."; form.reset(); renderFields(); });
  renderFields();
});
