document.addEventListener("DOMContentLoaded", () => {
  const catalog = window.vehicleCatalog || {}; if (!Object.keys(catalog).length) return;
  const demo = [{ name: "Rahul", rating: 5, comment: "Very clean and comfortable vehicle." }, { name: "Aisha", rating: 5, comment: "Smooth pickup and an excellent drive." }, { name: "Vikram", rating: 4, comment: "Great condition and helpful support." }];
  const read = (key, fallback) => { try { return JSON.parse(localStorage.getItem(key) || fallback); } catch { return JSON.parse(fallback); } };
  const stars = (number) => "★".repeat(Math.round(number)) + "☆".repeat(5 - Math.round(number));
  const reviewsFor = (id) => [...demo, ...(read("drivora-vehicle-reviews", "{}")[id] || [])];
  const summary = (id) => { const reviews = reviewsFor(id), v = catalog[id], userTotal = reviews.reduce((total, item) => total + Number(item.rating), 0); return { average: (v.rating * v.reviewCount + userTotal) / (v.reviewCount + reviews.length), count: v.reviewCount + reviews.length }; };
  const modal = document.createElement("div");
  modal.className = "booking-modal vehicle-detail-modal"; modal.hidden = true; modal.setAttribute("aria-hidden", "true");
  modal.innerHTML = `<div class="booking-modal__backdrop" data-close-details></div><section class="booking-modal__dialog vehicle-detail-dialog" role="dialog" aria-modal="true" aria-labelledby="vehicle-detail-title"><button class="booking-modal__close" type="button" data-close-details aria-label="Close vehicle details">&times;</button><div id="vehicle-detail-content"></div></section>`;
  document.body.append(modal); const content = modal.querySelector("#vehicle-detail-content"); let activeId = "";
  const close = () => { modal.hidden = true; modal.setAttribute("aria-hidden", "true"); };
  const renderInquiry = () => { const v = catalog[activeId]; content.innerHTML = `<p class="hero-badge">Vehicle inquiry</p><h2 id="vehicle-detail-title">Ask about ${v.name}</h2><form id="inquiry-form" novalidate><label>Name<input name="name" required></label><label>Email<input name="email" type="email" required></label><label>Phone<input name="phone" type="tel" inputmode="numeric" required></label><label>Vehicle name/model<input name="vehicle" value="${v.name}" readonly></label><label>Inquiry/question<textarea name="question" placeholder="Is this vehicle available for my dates?" required></textarea></label><p class="form-message" role="alert"></p><button class="btn btn-primary" type="submit">Send Inquiry</button></form>`; content.querySelector("form").addEventListener("submit", (event) => { event.preventDefault(); const form = event.currentTarget, data = Object.fromEntries(new FormData(form)), message = form.querySelector(".form-message"); if (!data.name.trim() || !data.question.trim() || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email) || !/^\d{10}$/.test(data.phone)) { message.textContent = "Enter your name, a valid email, 10-digit phone number, and question."; return; } const inquiries = read("drivora-vehicle-inquiries", "[]"); inquiries.push({ ...data, vehicleId: activeId, createdAt: new Date().toISOString() }); localStorage.setItem("drivora-vehicle-inquiries", JSON.stringify(inquiries)); form.innerHTML = `<p class="booking-success">✓ Inquiry Submitted Successfully</p><p>Your inquiry has been recorded. Our rental team will contact you shortly.</p>`; }); };
  const render = () => { const v = catalog[activeId], score = summary(activeId), reviews = reviewsFor(activeId); content.innerHTML = `<img class="detail-image" src="${v.image}" alt="${v.name}"><p class="hero-badge">${v.category}</p><h2 id="vehicle-detail-title">${v.name}</h2><p class="detail-specs">Model Year: ${v.modelYear} • ${v.transmission} • ${v.fuel} • ${v.seats} Seats</p><p class="vehicle-price">₹${v.price.toLocaleString("en-IN")}/day</p><p class="vehicle-rating" aria-label="Rated ${score.average.toFixed(1)} out of 5 stars">${stars(score.average)} ${score.average.toFixed(1)} (${score.count} Reviews)</p><p class="availability">● Available for booking</p><div class="detail-actions"><button class="btn btn-secondary inquiry-button" type="button">Ask About This Vehicle</button><button class="btn btn-primary detail-book-button" type="button">Book Now</button></div><section class="reviews-section"><h3>Reviews &amp; Ratings</h3><div class="review-list">${reviews.map((item) => `<article class="review"><span>${stars(item.rating)}</span><p>“${item.comment}”</p><strong>— ${item.name}</strong></article>`).join("")}</div><form id="review-form" novalidate><h3>Share your review</h3><label>Name<input name="name" required></label><label>Rating<select name="rating" required><option value="">Choose a rating</option><option value="5">5 - Excellent</option><option value="4">4 - Very good</option><option value="3">3 - Good</option><option value="2">2 - Fair</option><option value="1">1 - Poor</option></select></label><label>Review/comment<textarea name="comment" required></textarea></label><p class="form-message" role="alert"></p><button class="btn btn-primary" type="submit">Submit Review</button></form></section>`;
    content.querySelector(".detail-book-button").addEventListener("click", () => { close(); document.querySelector(`.book-button[data-vehicle="${v.name}"]`)?.click(); }); content.querySelector(".inquiry-button").addEventListener("click", renderInquiry);
    content.querySelector("#review-form").addEventListener("submit", (event) => { event.preventDefault(); const form = event.currentTarget, data = Object.fromEntries(new FormData(form)), message = form.querySelector(".form-message"); if (!data.name.trim() || !data.comment.trim() || !data.rating) { message.textContent = "Complete your name, rating, and review."; return; } const saved = read("drivora-vehicle-reviews", "{}"); saved[activeId] = [...(saved[activeId] || []), { name: data.name.trim(), rating: Number(data.rating), comment: data.comment.trim() }]; localStorage.setItem("drivora-vehicle-reviews", JSON.stringify(saved)); render(); }); };
  document.addEventListener("click", (event) => { const button = event.target.closest(".details-button"); if (!button) return; activeId = button.dataset.vehicleId; render(); modal.hidden = false; modal.setAttribute("aria-hidden", "false"); modal.querySelector(".booking-modal__close").focus(); });
  modal.querySelectorAll("[data-close-details]").forEach((button) => button.addEventListener("click", close)); document.addEventListener("keydown", (event) => { if (event.key === "Escape" && !modal.hidden) close(); });
});
